#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Animal")]
	public partial class AnimalTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnimalList(AnimalList instance);
    partial void UpdateAnimalList(AnimalList instance);
    partial void DeleteAnimalList(AnimalList instance);
    #endregion
		
		public AnimalTableDataContext() : 
				base(global::HumaneSociety.Properties.Settings.Default.AnimalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AnimalTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnimalTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnimalTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnimalTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnimalList> AnimalLists
		{
			get
			{
				return this.GetTable<AnimalList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnimalList")]
	public partial class AnimalList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnimalID;
		
		private string _AnimalCategory;
		
		private string _Name;
		
		private string _Type;
		
		private System.Nullable<int> _AgeYrs;
		
		private string _Gender;
		
		private System.Nullable<decimal> _WeightLBS;
		
		private string _PrimaryColor;
		
		private string _Temperament;
		
		private string _AdoptionStatus;
		
		private System.Nullable<decimal> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnimalIDChanging(int value);
    partial void OnAnimalIDChanged();
    partial void OnAnimalCategoryChanging(string value);
    partial void OnAnimalCategoryChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnAgeYrsChanging(System.Nullable<int> value);
    partial void OnAgeYrsChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnWeightLBSChanging(System.Nullable<decimal> value);
    partial void OnWeightLBSChanged();
    partial void OnPrimaryColorChanging(string value);
    partial void OnPrimaryColorChanged();
    partial void OnTemperamentChanging(string value);
    partial void OnTemperamentChanged();
    partial void OnAdoptionStatusChanging(string value);
    partial void OnAdoptionStatusChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    #endregion
		
		public AnimalList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimalID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnimalID
		{
			get
			{
				return this._AnimalID;
			}
			set
			{
				if ((this._AnimalID != value))
				{
					this.OnAnimalIDChanging(value);
					this.SendPropertyChanging();
					this._AnimalID = value;
					this.SendPropertyChanged("AnimalID");
					this.OnAnimalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimalCategory", DbType="VarChar(50)")]
		public string AnimalCategory
		{
			get
			{
				return this._AnimalCategory;
			}
			set
			{
				if ((this._AnimalCategory != value))
				{
					this.OnAnimalCategoryChanging(value);
					this.SendPropertyChanging();
					this._AnimalCategory = value;
					this.SendPropertyChanged("AnimalCategory");
					this.OnAnimalCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeYrs", DbType="Int")]
		public System.Nullable<int> AgeYrs
		{
			get
			{
				return this._AgeYrs;
			}
			set
			{
				if ((this._AgeYrs != value))
				{
					this.OnAgeYrsChanging(value);
					this.SendPropertyChanging();
					this._AgeYrs = value;
					this.SendPropertyChanged("AgeYrs");
					this.OnAgeYrsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightLBS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> WeightLBS
		{
			get
			{
				return this._WeightLBS;
			}
			set
			{
				if ((this._WeightLBS != value))
				{
					this.OnWeightLBSChanging(value);
					this.SendPropertyChanging();
					this._WeightLBS = value;
					this.SendPropertyChanged("WeightLBS");
					this.OnWeightLBSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryColor", DbType="VarChar(50)")]
		public string PrimaryColor
		{
			get
			{
				return this._PrimaryColor;
			}
			set
			{
				if ((this._PrimaryColor != value))
				{
					this.OnPrimaryColorChanging(value);
					this.SendPropertyChanging();
					this._PrimaryColor = value;
					this.SendPropertyChanged("PrimaryColor");
					this.OnPrimaryColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temperament", DbType="VarChar(50)")]
		public string Temperament
		{
			get
			{
				return this._Temperament;
			}
			set
			{
				if ((this._Temperament != value))
				{
					this.OnTemperamentChanging(value);
					this.SendPropertyChanging();
					this._Temperament = value;
					this.SendPropertyChanged("Temperament");
					this.OnTemperamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdoptionStatus", DbType="VarChar(50)")]
		public string AdoptionStatus
		{
			get
			{
				return this._AdoptionStatus;
			}
			set
			{
				if ((this._AdoptionStatus != value))
				{
					this.OnAdoptionStatusChanging(value);
					this.SendPropertyChanging();
					this._AdoptionStatus = value;
					this.SendPropertyChanged("AdoptionStatus");
					this.OnAdoptionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
