<?xml version="1.0" encoding="utf-8"?><Database Name="Animal" Class="AnimalTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WOLVERINE\WOLVERINE;Initial Catalog=Animal;Integrated Security=True" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="AnimalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnimalList" Member="AnimalLists">
    <Type Name="AnimalList">
      <Column Name="AnimalID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AnimalCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AgeYrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WeightLBS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PrimaryColor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Temperament" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdoptionStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>